# Generated by Django 4.1.2 on 2022-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imagenes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripcion"),
                ),
            ],
        ),
    ]
